---
# Variables that can provide as extra vars
VPC_REGION: eu-west-2 # N.Virginia
EC2_KEY_NAME: "compucorp-default-key"
LOCAL_USER_SSH_KEY: yes

# If you don't want to use any of this service, just set it's value to 'none'
# For example:
# If you want to use github ssh key as your key on the EC2, just mentioned your username
#
#
# and set the other variable as none or if you want to use local key over EC2 then do like this
#
# local_ssh_key: yes
# 

# Use inside the tasks
vpc_region: "{{ VPC_REGION }}"
local_user_ssh_key: "{{ LOCAL_USER_SSH_KEY }}"
ec2_key_name: "{{ EC2_KEY_NAME }}"