---
- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - add_keys

- hosts: webservers
  user: ubuntu
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get update && apt-get -y install python-simplejson

  roles:
    - ansible_users
