---
- name: Creating an AWS VPC inside mentioned Region
  ec2_vpc_net:
    name: "{{ vpc_name }}-vpc"
    region: "{{ vpc_region }}"
    cidr_block: "{{ vpc_cidr_block }}"
  register: vpc

# Exec Ansible with -vvv to proint debugging

- debug:
    var: vpc
    verbosity: 3

- name: Tag the Internet Gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_region }}"
    state: present
  register: igw

- name: Register subnets
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    region: "{{ vpc_region }}"
    resource_tags:
      Name: "{{ item.resource_tags.Name }}"
      Type: "{{ item.resource_tags.Type }}"
  register: subnets_tmp
  with_items: "{{ vpc_subnets }}"

- name: gather subnets from result
  set_fact: subnets="{{ subnets_tmp.results|map(attribute='subnet')|list }}"

- debug:
    var: subnets
    verbosity: 3

- name: Set up Public Subnets Route Table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_region }}"
    state: present
    resource_tags:
      Name: "Public-RT-for-{{ vpc_name }}-vpc"
    subnets: "{{ subnets | get_public_subnets_ids('Type','Public') }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  register: public_rt

- name: "Create {{ vpc_name }}.yml file inside the secret_vars directory"
  lineinfile: 
    dest: "secret_vars/{{ vpc_name }}.yml"
    line: "---"
    create: yes

- debug:
    var: public_rt
    verbosity: 3


- name: "Write vpc info to {{ vpc_name }}.yml file inside the secret_vars directory"
  lineinfile:
    dest: "secret_vars/{{ vpc_name }}.yml"
    regexp: "^{{ item.regexp | upper }}"
    line: "{{ item.regexp | upper }}: {{ '\"' + item.line + '\"' }}"
  with_items:
    - { regexp: 'vpc_id', line: '{{ vpc.vpc.id }}' }
    - { regexp: 'igw', line: '{{ igw.gateway_id }}' }
    - { regexp: 'route_table_id', line: '{{ public_rt.route_table.id }}' }

- name: "Write public and private subnets ids to {{ vpc_name }}.yml file inside the secret_vars directory"
  lineinfile:
    dest: "secret_vars/{{ vpc_name }}.yml"
    regexp: "^{{ item.item.resource_tags.Alias | upper }}"
    line: "{{ item.item.resource_tags.Alias | upper }}: {{ '\"' + item.subnet.id + '\"' }}"
  loop: "{{ subnets_tmp.results }}"

- include_vars: "secret_vars/{{ vpc_name }}.yml"