---
- name: Creating an AWS VPC inside mentioned Region
  ec2_vpc_net:
    name: "{{ vpc_name }}-vpc"
    region: "{{ vpc_region }}"
    cidr_block: "{{ vpc_cidr_block }}"
  register: vpc

# Exec Ansible with -vvv to proint debugging

- debug:
    var: vpc
    verbosity: 3

- name: Tag the Internet Gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_region }}"
    state: present
  register: igw

- name: Register subnets
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ item.cidr }}"
    region: "{{ vpc_region }}"
    resource_tags:
      Name: "{{ item.resource_tags.Name }}"
  register: subnets
  with_items: "{{ vpc_subnets }}"

- debug:
    var: vpc
    verbosity: 3

- debug:
    var: subnets
    verbosity: 0

- debug:
    var: "{{ item }}"
    verbosity: 0
  with_items: "{{ subnets }}"

- name: Set up Public Subnets Route Table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_region }}"
    state: present
    tags:
      - Name: "Public-RT-for-{{ vpc_name }}-vpc"
    subnets:
      - "{{ item.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ vpc.igw_id }}"
  with_items: "{{ subnets.results }}"
  register: public_rt

- name: "Create {{ vpc_name }}.yml file inside the secret_vars directory"
  lineinfile: 
    dest: "secret_vars/{{ vpc_name }}.yml"
    line: "---"
    create: yes

- name: "Write vpc info to {{ vpc_name }}.yml file inside the secret_vars directory"
  lineinfile:
    dest: "secret_vars/{{ vpc_name }}.yml"
    regexp: "^{{ item.regexp | upper }}"
    line: "{{ item.regexp | upper }}: {{ '\"' + item.line + '\"' }}"
  with_items:
    - { regexp: 'vpc_id', line: '{{ vpc.vpc_id }}' }
    - { regexp: 'igw', line: '{{ vpc.igw_id }}' }
    - { regexp: 'route_table_id', line: '{{ public_rt.route_table.id }}' }

- name: "Write public and private subnets ids to {{ vpc_name }}.yml file inside the secret_vars directory"
  lineinfile:
    dest: "secret_vars/{{ vpc_name }}.yml"
    regexp: "^{{ item.resource_tags.Alias | upper }}"
    line: "{{ item.resource_tags.Alias | upper }}: {{ '\"' + item.id + '\"' }}"
  with_items: "{{ vpc.subnets }}"
  
- include_vars: "secret_vars/{{ vpc_name }}.yml"